### ISSUE TITLE
Basic powder workflow for DREAM

### ISSUE THREAD

**Issue by jl-wynen** [scipp/essdiffraction#35]
- Load DREAM data (GEANT4 CSV)
- Compute d-spacing
- Save to XYE

Should serve as a starting point for the work in https://github.com/scipp/essdiffraction/milestone/1

**Comment by SimonHeybrock** [comment]
What is the difference to #25? Note that ESSdiffraction is past the `Skeleton` milestone already.

**Comment by jl-wynen** [comment]
My intention was to have a DREAM skeleton. And in this case, only have the bare bones. I.e., no normalisations. So we have a way to build up a workflow instead of having to put all pieces together at the same time in september.

**Comment by SimonHeybrock** [comment]
Sure, but add the task to the 'Essentials' milestone. No need to complicate things by adding new milestones, that we have kind of passed years ago.
