### ISSUE TITLE
Package structure for subtechniques

### ISSUE THREAD

**Issue by jl-wynen** [scipp/essdiffraction#9]
The current intention is that ESSdiffraction contains code for both powder and single crystal. But at this point, no SXD code has been added. Some existing code is provided in the root `ess.diffraction` package while some other functions are in `ess.diffraction.powder`.

It is unclear at this point what code can be shared between the techniques. The current split is based on a guess made in the old `ess` project and likely needs to be revised.

This is not a huge deal for regular functions and classes as those can easily be imported from wherever they are. But for Sciline providers, the split is more important because domain types used in the common `ess.diffraction.providers` must match pipelines in both powder and SXD. It is possible that we need to remove the shared provider list and only provide `ess.diffraction.{powder,sxd}.providers`.

See also this thread: https://github.com/scipp/essdiffraction/pull/7#discussion_r1415310288

**Comment by SimonHeybrock** [comment]
How about

```
ess.diffraction  #common
ess.powder
ess.sxd
ess.dream
ess.magic
```
?
